import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "ca" | "en" | "es";

const translations = {
  ca: {
    // Header
    nav_drop: "Col·lecció",
    nav_access: "Accés",
    nav_logout: "Sortir",

    hero_est: "Born in Barcelona",
    hero_title: "La muntanya és el patró.",
    hero_subtitle: "Cada drop és un territori. Cada peça en conserva la forma.",
    hero_mystery: "La home no ho revelarà tot. Entraràs, veuràs senyals, fragments i coordenades. El producte complet només apareix quan la comunitat el sap llegir.",
    hero_signal: "Senyal de llançament detectat",
    hero_metric_1_label: "Categoria",
    hero_metric_1_value: "Technical / Lifestyle",
    hero_metric_2_label: "Mercat",
    hero_metric_2_value: "Climbing niche",
    hero_metric_3_label: "Fase",
    hero_secondary_cta: "Inspeccionar el drop",
    hero_panel_label: "Drop intelligence",
    hero_panel_drop: "Actiu observat",
    hero_panel_availability: "Unitats",
    hero_panel_window: "Finestra",
    hero_panel_note_label: "Nota",
    hero_panel_note: "Els primers senyals no ensenyen la peça sencera. Només deixen clar que hi ha criteri, univers i ambició real al darrere.",
    hero_cta: "Desbloquejar accés",
    
    tease_label: "Descodificació",
    tease_title: "La intriga també pot vendre millor que una reveal plana.",
    tease_body: "Si vols que la gent entri i pensi ‘aquesta marca va seriosament’, la clau no és amagar-ho tot: és mostrar només el suficient perquè vulguin seguir estirant del fil.",
    tease_progress_label: "Claus obertes",
    tease_instruction: "Obre les tres pistes per entendre què s’acosta.",
    tease_locked: "Pista bloquejada. Hi ha informació, però encara no tota.",
    tease_clue_cta: "Tocar per revelar",
    tease_clue_open: "Pista revelada",
    tease_decode_label: "Missatge decodificat",
    tease_decoded_locked: "Quan les tres pistes estiguin obertes, apareixerà el relat complet del drop.",
    tease_decoded_helper: "Tens prou informació per veure el relat complet.",
    tease_decoded_title: "Un drop tècnic, cultural i limitat per a una comunitat molt concreta.",
    tease_decoded_body: "pdra. no surt per agradar a tothom. Surt per conquistar un públic que detecta detall, llenguatge propi i producte amb identitat. Aquesta sensació és la que la home ha de deixar des del primer scroll.",
    tease_clue_1_label: "Pista 01",
    tease_clue_1_body: "No és merch. És una peça construïda des del territori, amb una lectura tècnica i una direcció estètica molt controlada.",
    tease_clue_2_label: "Pista 02",
    tease_clue_2_body: "No busquem volum massiu. Busquem una comunitat petita però obsessionada amb el detall, la roca i el context cultural.",
    tease_clue_3_label: "Pista 03",
    tease_clue_3_body: "El drop sortirà pròximament. Fins llavors, cada bloc de la pàgina funciona com una filtració deliberada.",
    
    manifesto_label: "Manifest",
    manifesto_text: "pdra. neix de la roca, de la ciutat i de tot el que passa entre les dues.",
    manifesto_body: "No fem pantalons per semblar escaladors. Fem peces que porten territori a sobre. La muntanya no decora la roba: la construeix.",
    
    concept_label: "El concepte",
    concept_title: "Del relleu a la peça.",
    concept_p1: "Cada col·lecció parteix d’una serralada catalana. N’estudiem el perfil, les arestes, la tensió visual i la manera com el paisatge cau, talla i s’enfila.",
    concept_p2: "Després, tot això es tradueix en patronatge, volum i costures. No és outdoor convencional. No és streetwear buit. És escalada amb cultura.",
    
    drop_label: "Drop 001",
    drop_name: "MONTSERRAT",
    drop_subtitle: "La primera muntanya. El primer gest.",
    drop_elevation: "Altitud — 1.236 m",
    drop_units: "Edició limitada — {count} peces",
    drop_status_label: "Estat",
    drop_view: "Veure el drop",
    
    philosophy_label: "Filosofia",
    philosophy_title: "No parlem de rendiment. Parlem de connexió.",
    philosophy_body: "Escalar també és una manera de pertànyer a un lloc. pdra. converteix aquesta relació en roba que pots portar de la roca al carrer sense canviar de pell.",
    positioning_1_label: "Producte",
    positioning_1_body: "Peça limitada, lectura premium i detall suficient per justificar desig real.",
    positioning_2_label: "Narrativa",
    positioning_2_body: "No es comunica com un catàleg: es comunica com una investigació que s’està filtrant.",
    positioning_3_label: "Mercat",
    positioning_3_body: "Níxol, especialitzat i atractiu: escalada, cultura visual i identitat local amb aspiració global.",
    
    email_label: "Accés anticipat",
    email_title: "Entra abans que la resta.",
    email_supporting: "Accés a pistes, updates i obertura del drop abans que es faci públic.",
    email_on_list: "Ja formes part de la llista.",
    email_placeholder: "El teu email",
    email_cta: "Sol·licitar accés",
    
    timeline_label: "Road to drop",
    timeline_title: "Una home potent no explica tot el producte: administra tensió.",
    timeline_1_title: "Senyal",
    timeline_1_body: "Impacte visual, posicionament clar i una promesa difícil d’ignorar.",
    timeline_2_title: "Pistes",
    timeline_2_body: "Fragments del producte, llenguatge codificat i petites revelacions que fan avançar la curiositat.",
    timeline_3_title: "Drop",
    timeline_3_body: "Quan s’obri, la percepció ja estarà construïda: no descobriran només una peça, descobriran un univers.",
    drop_hint_line: "Més que un llançament: una filtració controlada.",
    drop_overlay: "Preview / classified",
    
    footer_location: "pdra. — Born in BCN. Made for the mountains.",

    // Drop Page
    drop_collection_label: "La Col·lecció",
    drop_collection_desc: "Nascuda de les crestes serrades de Montserrat, aquesta col·lecció tradueix la geometria impossible de la muntanya en forma vestible.",
    drop_back_cut: "El Tall de Muntanya Posterior — una línia de costura traçada des del perfil topogràfic del cim — defineix la silueta de cada peça.",
    drop_technical: "Tècnic",
    drop_fit: "Tall",
    drop_fit_value: "Ample",
    drop_composition: "Composició",
    drop_composition_value: "95% Cotó / 5% Elastà",
    drop_weight: "Gramatge",
    drop_weight_value: "280 gsm",
    drop_origin: "Origen",
    drop_origin_value: "Barcelona, ES",
    drop_elevation_label: "Altitud",
    drop_elevation_value: "1.236 m",
    drop_availability: "Disponibilitat",
    drop_units_remaining: "Unitats restants",
    drop_prebook: "Prereservar",
    drop_confirm_reservation: "Confirmar reserva — Talla {size}",
    drop_confirm: "Confirmar",
    drop_back: "Enrere",
    drop_reserved: "Reservat — Talla {size}",
    drop_production_soon: "La producció comença aviat.",
    drop_secured: "Has assegurat la teva peça.",
    drop_access_required: "Cal accés anticipat per prereservar.",
    drop_request_access: "Sol·licitar Accés",
    drop_coming_soon: "Pròximament",
    drop_open: "Obert",
    drop_sold_out: "Exhaurit",

    // Access Page
    access_granted: "Accés Concedit",
    access_welcome: "Benvingut/da.",
    access_early: "Tens accés anticipat a totes les col·leccions.",
    access_enter: "Entrar a la Col·lecció",
    access_requested: "Sol·licitat",
    access_reviewing: "La teva sol·licitud s'està revisant.",
    access_reach_out: "Et contactarem quan el teu accés estigui llest.",
    access_simulate: "(Simular aprovació)",
    access_request: "Sol·licitar Accés",
    access_login: "Entrar",
    access_enter_btn: "Entrar",

    // Admin
    admin_title: "Admin — Panell de Prova",
    admin_drop_status: "Estat de la Col·lecció",
    admin_current_state: "Estat Actual",
    admin_status: "Estat",
    admin_units: "Unitats",
    admin_user: "Usuari",
    admin_access: "Accés",
  },

  en: {
    nav_drop: "Drop",
    nav_access: "Access",
    nav_logout: "Logout",

    hero_est: "Born in Barcelona",
    hero_title: "The mountain is the pattern.",
    hero_subtitle: "Each drop is a territory. Each piece carries its shape.",
    hero_mystery: "The homepage should not reveal everything. Visitors should find signals, fragments, and coordinates. The full product only appears once the community knows how to read it.",
    hero_signal: "Launch signal detected",
    hero_metric_1_label: "Category",
    hero_metric_1_value: "Technical / Lifestyle",
    hero_metric_2_label: "Market",
    hero_metric_2_value: "Climbing niche",
    hero_metric_3_label: "Phase",
    hero_secondary_cta: "Inspect the drop",
    hero_panel_label: "Drop intelligence",
    hero_panel_drop: "Observed asset",
    hero_panel_availability: "Units",
    hero_panel_window: "Window",
    hero_panel_note_label: "Note",
    hero_panel_note: "The first signals do not show the full garment. They only prove there is taste, world-building, and real ambition behind it.",
    hero_cta: "Unlock access",
    
    tease_label: "Decoding",
    tease_title: "Mystery can sell harder than a flat reveal.",
    tease_body: "If you want people to enter and think ‘this brand is serious’, the key is not hiding everything: it is showing just enough to make them keep pulling the thread.",
    tease_progress_label: "Unlocked clues",
    tease_instruction: "Open all three clues to understand what is coming.",
    tease_locked: "Clue locked. There is information here, but not all of it yet.",
    tease_clue_cta: "Tap to reveal",
    tease_clue_open: "Clue revealed",
    tease_decode_label: "Decoded message",
    tease_decoded_locked: "Once all three clues are open, the full narrative of the drop will appear.",
    tease_decoded_helper: "You have enough information to see the full narrative.",
    tease_decoded_title: "A technical, cultural, limited drop for a very specific community.",
    tease_decoded_body: "pdra. is not launching to please everyone. It is launching to win over a public that notices detail, distinct language, and product with identity. The homepage should make that clear in the very first scroll.",
    tease_clue_1_label: "Clue 01",
    tease_clue_1_body: "This is not merch. It is a garment built from territory, with technical intent and tightly controlled aesthetic direction.",
    tease_clue_2_label: "Clue 02",
    tease_clue_2_body: "The goal is not mass volume. The goal is a small community obsessed with detail, rock, and cultural context.",
    tease_clue_3_label: "Clue 03",
    tease_clue_3_body: "The drop is coming soon. Until then, every homepage block works like a deliberate leak.",
    
    manifesto_label: "Manifesto",
    manifesto_text: "pdra. is born from rock, from the city, and from everything that lives between the two.",
    manifesto_body: "We do not make climbing pants to look like climbers. We make garments that carry territory. The mountain is not decoration — it builds the piece.",
    
    concept_label: "The Concept",
    concept_title: "From landscape to garment.",
    concept_p1: "Each collection begins with a Catalan mountain range. We study its profile, ridgelines, visual tension, and the way the land rises, cuts, and falls.",
    concept_p2: "Then we translate it into pattern, volume, and seam construction. It is not conventional outdoor wear. It is not empty streetwear. It is climbing with culture.",
    
    drop_label: "Drop 001",
    drop_name: "MONTSERRAT",
    drop_subtitle: "The first mountain. The first gesture.",
    drop_elevation: "Elevation — 1,236 m",
    drop_units: "Limited edition — {count} pieces",
    drop_status_label: "Status",
    drop_view: "View the drop",
    
    philosophy_label: "Philosophy",
    philosophy_title: "This is not about performance. It is about connection.",
    philosophy_body: "Climbing is also a way of belonging to a place. pdra. turns that relationship into clothing you can carry from rock to city without changing your skin.",
    positioning_1_label: "Product",
    positioning_1_body: "Limited garment, premium reading, and enough detail to justify real desire.",
    positioning_2_label: "Narrative",
    positioning_2_body: "It should not communicate like a catalog. It should communicate like an investigation slowly leaking out.",
    positioning_3_label: "Market",
    positioning_3_body: "Niche, specialized, and compelling: climbing, visual culture, and local identity with global ambition.",
    
    email_label: "Early access",
    email_title: "Enter before everyone else.",
    email_supporting: "Access clues, updates, and the opening of the drop before it goes public.",
    email_on_list: "You are already on the list.",
    email_placeholder: "Your email",
    email_cta: "Request access",
    
    timeline_label: "Road to drop",
    timeline_title: "A strong homepage does not explain the full product. It manages tension.",
    timeline_1_title: "Signal",
    timeline_1_body: "Visual impact, clear positioning, and a promise that is hard to ignore.",
    timeline_2_title: "Clues",
    timeline_2_body: "Product fragments, coded language, and small reveals that keep curiosity moving.",
    timeline_3_title: "Drop",
    timeline_3_body: "When it opens, perception is already built: visitors will not only discover a piece, they will discover a universe.",
    drop_hint_line: "More than a launch: a controlled leak.",
    drop_overlay: "Preview / classified",
    
    footer_location: "pdra. — Born in BCN. Made for the mountains.",

    drop_collection_label: "The Collection",
    drop_collection_desc: "Born from the serrated ridges of Montserrat, this collection translates the mountain's impossible geometry into wearable form.",
    drop_back_cut: "The Back Mountain Cut — a single seam line traced from the peak's topographic profile — defines the silhouette of each piece.",
    drop_technical: "Technical",
    drop_fit: "Fit",
    drop_fit_value: "Wide",
    drop_composition: "Composition",
    drop_composition_value: "95% Cotton / 5% Elastane",
    drop_weight: "Weight",
    drop_weight_value: "280 gsm",
    drop_origin: "Origin",
    drop_origin_value: "Barcelona, ES",
    drop_elevation_label: "Elevation",
    drop_elevation_value: "1,236 m",
    drop_availability: "Availability",
    drop_units_remaining: "Units remaining",
    drop_prebook: "Prebook",
    drop_confirm_reservation: "Confirm reservation — Size {size}",
    drop_confirm: "Confirm",
    drop_back: "Back",
    drop_reserved: "Reserved — Size {size}",
    drop_production_soon: "Production starts soon.",
    drop_secured: "You secured your piece.",
    drop_access_required: "Early access required to prebook.",
    drop_request_access: "Request Access",
    drop_coming_soon: "Coming soon",
    drop_open: "Open",
    drop_sold_out: "Sold out",

    access_granted: "Access Granted",
    access_welcome: "Welcome back.",
    access_early: "You have early access to all drops.",
    access_enter: "Enter Drop",
    access_requested: "Requested",
    access_reviewing: "Your request is being reviewed.",
    access_reach_out: "We'll reach out when your access is ready.",
    access_simulate: "(Simulate approval)",
    access_request: "Request Access",
    access_login: "Login",
    access_enter_btn: "Enter",

    admin_title: "Admin — Mock Panel",
    admin_drop_status: "Drop Status",
    admin_current_state: "Current State",
    admin_status: "Status",
    admin_units: "Units",
    admin_user: "User",
    admin_access: "Access",
  },

  es: {
    nav_drop: "Colección",
    nav_access: "Acceso",
    nav_logout: "Salir",

    hero_est: "Born in Barcelona",
    hero_title: "La montaña es el patrón.",
    hero_subtitle: "Cada drop es un territorio. Cada pieza conserva su forma.",
    hero_mystery: "La home no debería revelarlo todo. La gente debe encontrar señales, fragmentos y coordenadas. El producto completo solo aparece cuando la comunidad sabe leerlo.",
    hero_signal: "Señal de lanzamiento detectada",
    hero_metric_1_label: "Categoría",
    hero_metric_1_value: "Technical / Lifestyle",
    hero_metric_2_label: "Mercado",
    hero_metric_2_value: "Climbing niche",
    hero_metric_3_label: "Fase",
    hero_secondary_cta: "Inspeccionar el drop",
    hero_panel_label: "Drop intelligence",
    hero_panel_drop: "Activo observado",
    hero_panel_availability: "Unidades",
    hero_panel_window: "Ventana",
    hero_panel_note_label: "Nota",
    hero_panel_note: "Las primeras señales no enseñan la prenda entera. Solo demuestran que detrás hay criterio, universo y ambición real.",
    hero_cta: "Desbloquear acceso",
    
    tease_label: "Decodificación",
    tease_title: "La intriga también puede vender mejor que una reveal plana.",
    tease_body: "Si quieres que la gente entre y piense ‘esta marca va en serio’, la clave no es ocultarlo todo: es enseñar solo lo suficiente para que quieran seguir tirando del hilo.",
    tease_progress_label: "Claves abiertas",
    tease_instruction: "Abre las tres pistas para entender lo que se acerca.",
    tease_locked: "Pista bloqueada. Aquí hay información, pero todavía no toda.",
    tease_clue_cta: "Tocar para revelar",
    tease_clue_open: "Pista revelada",
    tease_decode_label: "Mensaje decodificado",
    tease_decoded_locked: "Cuando las tres pistas estén abiertas, aparecerá el relato completo del drop.",
    tease_decoded_helper: "Ya tienes suficiente información para ver el relato completo.",
    tease_decoded_title: "Un drop técnico, cultural y limitado para una comunidad muy concreta.",
    tease_decoded_body: "pdra. no sale para gustar a todo el mundo. Sale para conquistar a un público que detecta detalle, lenguaje propio y producto con identidad. Esa sensación debe quedar clara en el primer scroll.",
    tease_clue_1_label: "Pista 01",
    tease_clue_1_body: "No es merch. Es una prenda construida desde el territorio, con lectura técnica y una dirección estética muy controlada.",
    tease_clue_2_label: "Pista 02",
    tease_clue_2_body: "No buscamos volumen masivo. Buscamos una comunidad pequeña pero obsesionada con el detalle, la roca y el contexto cultural.",
    tease_clue_3_label: "Pista 03",
    tease_clue_3_body: "El drop saldrá próximamente. Hasta entonces, cada bloque de la página funciona como una filtración deliberada.",
    
    manifesto_label: "Manifiesto",
    manifesto_text: "pdra. nace de la roca, de la ciudad y de todo lo que ocurre entre las dos.",
    manifesto_body: "No hacemos pantalones para parecer escaladores. Hacemos prendas que llevan territorio encima. La montaña no decora la ropa: la construye.",
    
    concept_label: "El concepto",
    concept_title: "Del relieve a la prenda.",
    concept_p1: "Cada colección parte de una sierra catalana. Estudiamos su perfil, sus aristas, su tensión visual y la forma en que el paisaje sube, corta y cae.",
    concept_p2: "Después, todo eso se traduce en patronaje, volumen y costuras. No es outdoor convencional. No es streetwear vacío. Es escalada con cultura.",
    
    drop_label: "Drop 001",
    drop_name: "MONTSERRAT",
    drop_subtitle: "La primera montaña. El primer gesto.",
    drop_elevation: "Altitud — 1.236 m",
    drop_units: "Edición limitada — {count} piezas",
    drop_status_label: "Estado",
    drop_view: "Ver el drop",
    
    philosophy_label: "Filosofía",
    philosophy_title: "No hablamos de rendimiento. Hablamos de conexión.",
    philosophy_body: "Escalar también es una forma de pertenecer a un lugar. pdra. convierte esa relación en ropa que puedes llevar de la roca a la ciudad sin cambiar de piel.",
    positioning_1_label: "Producto",
    positioning_1_body: "Prenda limitada, lectura premium y detalle suficiente para justificar deseo real.",
    positioning_2_label: "Narrativa",
    positioning_2_body: "No debe comunicarse como un catálogo: debe sentirse como una investigación que se va filtrando.",
    positioning_3_label: "Mercado",
    positioning_3_body: "Nicho, especializado y atractivo: escalada, cultura visual e identidad local con ambición global.",
    
    email_label: "Acceso anticipado",
    email_title: "Entra antes que el resto.",
    email_supporting: "Acceso a pistas, updates y apertura del drop antes de que se haga público.",
    email_on_list: "Ya formas parte de la lista.",
    email_placeholder: "Tu email",
    email_cta: "Solicitar acceso",
    
    timeline_label: "Road to drop",
    timeline_title: "Una home potente no explica todo el producto: administra tensión.",
    timeline_1_title: "Señal",
    timeline_1_body: "Impacto visual, posicionamiento claro y una promesa difícil de ignorar.",
    timeline_2_title: "Pistas",
    timeline_2_body: "Fragmentos del producto, lenguaje codificado y pequeñas revelaciones que hacen avanzar la curiosidad.",
    timeline_3_title: "Drop",
    timeline_3_body: "Cuando se abra, la percepción ya estará construida: no descubrirán solo una prenda, descubrirán un universo.",
    drop_hint_line: "Más que un lanzamiento: una filtración controlada.",
    drop_overlay: "Preview / classified",
    
    footer_location: "pdra. — Born in BCN. Made for the mountains.",

    drop_collection_label: "La Colección",
    drop_collection_desc: "Nacida de las crestas serradas de Montserrat, esta colección traduce la geometría imposible de la montaña en forma vestible.",
    drop_back_cut: "El Corte de Montaña Posterior — una línea de costura trazada desde el perfil topográfico del pico — define la silueta de cada pieza.",
    drop_technical: "Técnico",
    drop_fit: "Corte",
    drop_fit_value: "Amplio",
    drop_composition: "Composición",
    drop_composition_value: "95% Algodón / 5% Elastano",
    drop_weight: "Gramaje",
    drop_weight_value: "280 gsm",
    drop_origin: "Origen",
    drop_origin_value: "Barcelona, ES",
    drop_elevation_label: "Altitud",
    drop_elevation_value: "1.236 m",
    drop_availability: "Disponibilidad",
    drop_units_remaining: "Unidades restantes",
    drop_prebook: "Prereservar",
    drop_confirm_reservation: "Confirmar reserva — Talla {size}",
    drop_confirm: "Confirmar",
    drop_back: "Atrás",
    drop_reserved: "Reservado — Talla {size}",
    drop_production_soon: "La producción comienza pronto.",
    drop_secured: "Has asegurado tu pieza.",
    drop_access_required: "Se requiere acceso anticipado para prereservar.",
    drop_request_access: "Solicitar Acceso",
    drop_coming_soon: "Próximamente",
    drop_open: "Abierto",
    drop_sold_out: "Agotado",

    access_granted: "Acceso Concedido",
    access_welcome: "Bienvenido/a.",
    access_early: "Tienes acceso anticipado a todas las colecciones.",
    access_enter: "Entrar a la Colección",
    access_requested: "Solicitado",
    access_reviewing: "Tu solicitud está siendo revisada.",
    access_reach_out: "Te contactaremos cuando tu acceso esté listo.",
    access_simulate: "(Simular aprobación)",
    access_request: "Solicitar Acceso",
    access_login: "Entrar",
    access_enter_btn: "Entrar",

    admin_title: "Admin — Panel de Prueba",
    admin_drop_status: "Estado de la Colección",
    admin_current_state: "Estado Actual",
    admin_status: "Estado",
    admin_units: "Unidades",
    admin_user: "Usuario",
    admin_access: "Acceso",
  },
} as const;

type TranslationKey = keyof typeof translations.ca;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ca");

  const t = (key: TranslationKey, params?: Record<string, string | number>): string => {
    let text: string = translations[language][key] || translations.ca[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export const languageLabels: Record<Language, string> = {
  ca: "CA",
  en: "EN",
  es: "ES",
};
